### ISSUE TITLE
Update Services git repo link in README file

### ISSUE THREAD

**Issue by csankhala** [csankhala/ecommerce-micronaut-kafka#2]
Search services repo here: https://github.com/search?q=csankhala-ecommerce&type=repositories

Update README link

![Image](https://user-images.githubusercontent.com/13249132/236457709-07d40ba3-fe3e-4144-ad76-80d5a62377b8.png)

**Comment by Subham5401** [comment]
Hey @csankhala, I'd like to take this further, can you elaborate a lil about the issue and your requirement?

**Comment by csankhala** [comment]
sure,
there is list of services listed in readme file.
few services has broken link.

you can find correct repo link from given search link.

**Comment by Subham5401** [comment]
Ohk, thanks for responding!
